// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE9mHsLmlej-zoqL6ahcH1cH4sMU5ksmo',
    appId: '1:71495362807:web:18dfe3b304e8c6a4ee4bf2',
    messagingSenderId: '71495362807',
    projectId: 'flutter-project-ce8a9',
    authDomain: 'flutter-project-ce8a9.firebaseapp.com',
    storageBucket: 'flutter-project-ce8a9.appspot.com',
    measurementId: 'G-TT1ELNXGX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1WZuGGQAf1Yr_cl1Tl6hiHVoAi9V78s',
    appId: '1:71495362807:android:ab42d35cc59c3d97ee4bf2',
    messagingSenderId: '71495362807',
    projectId: 'flutter-project-ce8a9',
    storageBucket: 'flutter-project-ce8a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtU3vSJNKoO4vlyWbzsFHTI9yl95hyqeA',
    appId: '1:71495362807:ios:8872c136385a1ca3ee4bf2',
    messagingSenderId: '71495362807',
    projectId: 'flutter-project-ce8a9',
    storageBucket: 'flutter-project-ce8a9.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtU3vSJNKoO4vlyWbzsFHTI9yl95hyqeA',
    appId: '1:71495362807:ios:e56de7ee443c465aee4bf2',
    messagingSenderId: '71495362807',
    projectId: 'flutter-project-ce8a9',
    storageBucket: 'flutter-project-ce8a9.appspot.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
